### ISSUE TITLE
Hangs Firefox and Chrome

### ISSUE THREAD

**Issue by newstler** [LRDesign/NinjaScript#2]
Hangs on string 25:

return list.forEach(callback, thisArg)

and all I can do is close the page.

**Comment by IdahoEv** [comment]
Which version of jQuery are you using?   There is a known issue with JQuery 1.4.3, 1.4.4, and 1.5 that causes the behavior you describe in the current version of NinjaScript.   0.8.3) 

In the current version, NinjaScript requires jQuery 1.4.2.   We will be fixing this in the next major release of NinjaScript.

**Comment by IdahoEv** [comment]
I have added documentation to this effect the the README.

**Comment by newstler** [comment]
Thank you! I am using 1.5 becouse of some bug that appeared in 1.4, so I have to wait untill next major version of NinjaScript will be released.

**Comment by nyarly** [comment]
We're working on it.   Believe me, we want to be able to use 1.5 as much as you do

**Comment by LRDesign** [comment]
The current release works with all versions of jQuery 1.4+, including 1.5 and 1.6.   Enjoy!

**Comment by newstler** [comment]
Cool! Thanx!! ))

**Comment by nyarly** [comment]
We're pretty chuffed ourselves.  Please let us know if you have any problems, comments, or win :)
